name: test
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - attrs=20.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - blosc=1.20.0=h7bd577a_0
  - bokeh=2.2.1=py38_0
  - brotlipy=0.7.0=py38he774522_1000
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.6.20=hecda079_0
  - catalogue=1.0.0=py_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.3=py38h7a1dbc1_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1.1=py38h7a1dbc1_0
  - cudatoolkit=10.2.89=h74a9793_1
  - cycler=0.10.0=py38_0
  - cymem=2.0.3=py38h7ae7562_2
  - cython-blis=0.4.1=py38h9de7a3e_1
  - cytoolz=0.11.0=py38he774522_0
  - dask=2.27.0=py_0
  - dask-core=2.27.0=py_0
  - distributed=2.27.0=py38_0
  - freetype=2.10.2=hd328e21_0
  - fsspec=0.8.0=py_0
  - hdf5=1.10.4=h7ebc959_0
  - heapdict=1.0.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py38h32f6830_0
  - importlib_metadata=2.0.0=0
  - intel-openmp=2020.2=254
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py38h32f6830_1
  - kiwisolver=1.2.0=py38h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - locket=0.2.0=py38_1
  - lz4-c=1.9.2=h62dcd97_1
  - lzo=2.10=vc14h0a64fa6_1
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38hba9282a_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.1.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - mock=4.0.2=py_0
  - msgpack-python=1.0.0=py38h74a9793_1
  - murmurhash=1.0.0=py38hb99c5c2_0
  - ninja=1.10.1=py38h7ef1ec2_0
  - numexpr=2.7.1=py38h25d0782_0
  - numpy=1.19.1=py38h5510c5b_0
  - numpy-base=1.19.1=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pandas=1.1.1=py38ha925a31_0
  - partd=1.1.0=py_0
  - pillow=7.2.0=py38hcc1f983_0
  - pip=20.2.2=py38_0
  - plac=0.9.6=py38_1
  - preshed=3.0.2=py38h7ae7562_3
  - psutil=5.7.2=py38he774522_0
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyrsistent=0.17.3=py38h1e8a9f7_0
  - pysocks=1.7.1=py38_0
  - pytables=3.6.1=py38ha5be198_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.6.0=py3.8_cuda102_cudnn7_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py38he774522_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.24.0=py_0
  - scikit-learn=0.23.2=py38h47e9c7a_0
  - scipy=1.5.0=py38h9439919_0
  - setuptools=49.6.0=py38_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py_0
  - snappy=1.1.8=h33f27b4_0
  - sortedcontainers=2.2.2=py_0
  - spacy=2.3.2=py38h95a2b95_0
  - sqlite=3.33.0=h2a8f88b_0
  - srsly=1.0.2=py38h7ae7562_0
  - tblib=1.7.0=py_0
  - thinc=7.4.1=py38h95a2b95_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=he774522_0
  - toolz=0.10.0=py_0
  - torchtext=0.7.0=py38
  - torchvision=0.7.0=py38_cu102
  - tornado=6.0.4=py38he774522_1
  - tqdm=4.49.0=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.10=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wasabi=0.8.0=pyh9f0ad1d_0
  - wheel=0.35.1=py_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - zict=2.0.0=py_0
  - zipp=3.2.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - bcolz==1.2.2.dev12
    - en-core-web-sm==2.3.1
    - filelock==3.0.12
    - regex==2020.7.14
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tokenizers==0.8.1rc2
    - transformers==3.1.0
prefix: C:\Users\sylke\AppData\Local\Continuum\anaconda3\envs\question_classification

